# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- develop

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'Docker hub'
        repository: 'phillmac/py-orbit-db-http-client-dev'
        command: build
        dockerfile: '**/Dockerfile'
        tags: |
          latest
          $(tag)
    - task: Docker@2
      displayName: Push image
      inputs:
        containerRegistry: 'Docker hub'
        repository: 'phillmac/py-orbit-db-http-client-dev'
        command: 'push'
        tags: |
          latest
          $(tag)
    - task: TriggerBuild@3
      inputs:
        definitionIsInCurrentTeamProject: false
        tfsServer: 'https://phillmac.visualstudio.com'
        teamProject: '804fe699-2025-46ad-b3c1-29bd8f6e974d'
        buildDefinition: 'phillmac.orbit-db-http-api-tests'
        queueBuildForUserThatTriggeredBuild: false
        ignoreSslCertificateErrors: false
        useSameSourceVersion: false
        useSameBranch: false
        branchToUse: 'master'
        waitForQueuedBuildsToFinish: true
        waitForQueuedBuildsToFinishRefreshTime: '30'
        failTaskIfBuildsNotSuccessful: true
        cancelBuildsIfAnyFails: false
        treatPartiallySucceededBuildAsSuccessful: false
        downloadBuildArtifacts: false
        storeInEnvironmentVariable: false
        authenticationMethod: 'OAuth Token'
        enableBuildInQueueCondition: false
        dependentOnSuccessfulBuildCondition: false
        dependentOnFailedBuildCondition: false
        checkbuildsoncurrentbranch: false
        failTaskIfConditionsAreNotFulfilled: false