# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- develop

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'OrbitDB Docker Hub'
        repository: 'phillmac/py-orbit-db-http-client-dev'
        command: build
        dockerfile: '**/Dockerfile'
        tags: |
          latest
          $(tag)
    - task: Docker@2
      displayName: Push image
      inputs:
        containerRegistry: 'OrbitDB Docker Hub'
        repository: 'phillmac/py-orbit-db-http-client-dev'
        command: 'push'
        tags: |
          latest
          $(tag)